name: CI

on: [push,pull_request,workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-20.04]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          submodules: true
      - name: step1
        run: bash -c "pwd;  ls -la"
      - name: install dependencies
        run: sudo bash ./install.sh
      - name: build binaries
        run: bash ./build.sh
      - name: check binaries
        run: bash ./check.sh
      - name: test changes
        run: bash ./test.sh
