name: CI

on: [push,pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:21.04

    steps:
      - name: step1
        run: bash -c "pwd;  ls -la"
      - name: install sudo and git
        run: apt update && apt install -y sudo git
      - name: check git version
        run: git version
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          submodules: true
      - name: install dependencies
        run: sudo bash ./install.sh
      - name: step1
        run: bash -c "pwd;  ls -la"
      - name: build binaries
        run: bash ./build.sh
      - name: check binaries
        run: bash ./check.sh
      - name: test changes
        run: bash ./test.sh
